server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
#    url: jdbc:h2:mem:cosdb
#    driver-class-name: org.h2.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cos?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa: 
    hibernate:
      ddl-auto: update # create, update, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    format-sql: true
    show-sql: true
logging:
  level:
    org.hibernate: 
    org.hibernate.type.descriptor.sql: trace
    SQL: DEBUG